// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Templates.Infrastructure.Persistence;

#nullable disable

namespace Templates.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TemplatesDbContext))]
    [Migration("20260704220135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Templates.Domain.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_templates_tenant_id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("Templates.Domain.Template", b =>
                {
                    b.OwnsOne("Templates.Domain.TemplateContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("subject");

                            b1.HasKey("TemplateId");

                            b1.ToTable("templates");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.OwnsOne("Templates.Domain.TemplateName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");

                            b1.HasKey("TemplateId");

                            b1.ToTable("templates");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
